name: Try Run This Action
on:
  push:
    branches: ["*"]
    tags: ["v*"]
  pull_request:
    branches: [master]
  workflow_dispatch:

jobs:
  check:
    name: Run this GitHub Action
    runs-on: ubuntu-latest
    outputs:
      is_update: ${{ steps.check_ver.outputs.is_update }}
      result: ${{ steps.check_ver.outputs.result }}
      docker_tags: ${{ steps.check_ver.outputs.docker_tags }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Lint check
        run: yarn lint
      - name: Test this actions
        id: check_ver
        uses: ./
        with:
          repo: mogeko/latest-version
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: metadata
          path: ./.latest-version/index.json

  print:
    name: Print the result from check
    runs-on: ubuntu-latest
    needs: check
    steps:
      - name: Print Output
        run: |
          echo '${{ needs.check.outputs.is_update }}'
          echo '${{ needs.check.outputs.result }}' | jq '.'
          echo '${{ needs.check.outputs.docker_tags }}'
      - name: If is_update is true
        if: needs.check.outputs.is_update == 'true'
        run: echo "It seems to have updates."
      - name: If is_update is false
        if: needs.check.outputs.is_update == 'false'
        run: echo "It seems to have no updates."
