name: Test
on:
  push:
    branches-ignore: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    name: Test GitHub Action
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: yarn
      - name: Lint check
        run: yarn lint
