name: Test
on:
  push:
  pull_request:
    branches: [master]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  check:
    name: Test GitHub Action
    runs-on: ubuntu-latest
    outputs:
      result: ${{ steps.check_ver.outputs.result }}
      edge: ${{ steps.check_ver.outputs.edge }}
      latest: ${{ steps.check_ver.outputs.latest }}
      is_update: ${{ steps.check_ver.outputs.is_update }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v2
      - name: Lint check
        run: yarn lint
      - name: Test this actions
        id: check_ver
        uses: ./
        with:
          repo: mogeko/latest-version
          refer: ${{ steps.pages.outputs.base_url }}
          out: true
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./latest-version

  print:
    name: Print the result from check
    runs-on: ubuntu-latest
    needs: check
    steps:
      - name: Print Output
        run: |
          echo "${{ needs.check.outputs.result }}"
          echo "${{ needs.check.outputs.edge }}"
          echo "${{ needs.check.outputs.latest }}"
          echo "${{ needs.check.outputs.is_update }}"
      - name: If is_update is true
        if: ${{ needs.check.outputs.is_update }} == 'true'
        run: echo "It seems to have updates."
      - name: If is_update is false
        if: ${{ needs.check.outputs.is_update }} == 'false'
        run: echo "It seems to have no updates."

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    if: github.ref_name == 'master'
    runs-on: ubuntu-latest
    needs: check
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
